Repository OTI-SRM/srm_project, pull requests merged in 2023-02, with the labels that each got.

#24 [#2]
  src/main/java/com/oti/team2/HomeController.java
  src/main/java/com/oti/team2/exampleController.java
  src/main/webapp/WEB-INF/views/board/notice-detail.jsp
  src/main/webapp/WEB-INF/views/board/notice-update.jsp
  src/main/webapp/WEB-INF/views/board/notice-write.jsp
  src/main/webapp/WEB-INF/views/board/noticeList.jsp
  src/main/webapp/WEB-INF/views/board/qna-detail.jsp
  src/main/webapp/WEB-INF/views/board/qna-update.jsp
  src/main/webapp/WEB-INF/views/board/qna-write.jsp
  src/main/webapp/WEB-INF/views/board/qnaList.jsp
  src/main/webapp/WEB-INF/views/example.jsp
  src/main/webapp/WEB-INF/views/fragments/bottom.jsp
  src/main/webapp/WEB-INF/views/fragments/header.jsp
  src/main/webapp/WEB-INF/views/fragments/pagination.jsp
  src/main/webapp/WEB-INF/views/fragments/sidebar.jsp
  src/main/webapp/WEB-INF/views/member/addInst.jsp
  src/main/webapp/WEB-INF/views/member/checkPw.jsp
  src/main/webapp/WEB-INF/views/member/join-client.jsp
  src/main/webapp/WEB-INF/views/member/join-employee.jsp
  src/main/webapp/WEB-INF/views/member/login.jsp
  src/main/webapp/WEB-INF/views/member/my-todo.jsp
  src/main/webapp/WEB-INF/views/member/myInst.jsp
  src/main/webapp/WEB-INF/views/member/myinfo.jsp
  src/main/webapp/WEB-INF/views/srDemand/srDemandList.jsp
  src/main/webapp/WEB-INF/views/srInfo/srInformationList.jsp
  src/main/webapp/resources/css/srButton.css
  src/main/webapp/resources/js/kakaoAddress.js
  src/main/webapp/resources/js/pagination.js
  src/main/webapp/resources/oti_images/newPost.png
Labels: 화면 구현

#34 [#29] 고객관리 기능 구현
  .gitignore
  src/main/java/com/oti/team2/HomeController.java
  src/main/java/com/oti/team2/admin/controller/AdminController.java
  src/main/java/com/oti/team2/exampleController.java
  src/main/java/com/oti/team2/institution/dao/InstitutionDao.java
  src/main/java/com/oti/team2/institution/dto/Institution.java
  src/main/java/com/oti/team2/institution/service/IInstitutionService.java
  src/main/java/com/oti/team2/institution/service/InstitutionService.java
  src/main/java/com/oti/team2/member/controller/MemberController.java
  src/main/java/com/oti/team2/member/dao/IMemberDao.java
  src/main/java/com/oti/team2/member/dto/Member.java
  src/main/java/com/oti/team2/member/dto/ProfileImg.java
  src/main/java/com/oti/team2/member/service/IMemberService.java
  src/main/java/com/oti/team2/member/service/MemberService.java
  src/main/java/com/oti/team2/util/Auth.java
  src/main/java/com/oti/team2/util/pager/Pager.java
  src/main/resources/mybatis/mapper-config.xml
  src/main/resources/mybatis/mapper/Member.xml
  src/main/resources/mybatis/mapper/institution.xml
  src/main/resources/spring/component_scan.xml
  src/main/resources/spring/mybatis.xml
  src/main/webapp/WEB-INF/views/management/clientList.jsp
  src/main/webapp/WEB-INF/views/member/myinfo.jsp
Labels: 기능 구현, 추가 구현 필요

#42 [#40] SR요청CRUD, 결재 기능 구현
  src/main/java/com/oti/team2/SrDemand.java
  src/main/java/com/oti/team2/exampleController.java
  src/main/java/com/oti/team2/institution/service/InstitutionService.java
  src/main/java/com/oti/team2/member/dao/IMemberDao.java
  src/main/java/com/oti/team2/member/service/IMemberService.java
  src/main/java/com/oti/team2/member/service/MemberService.java
  src/main/java/com/oti/team2/srdemand/controller/SrDemandController.java
  src/main/java/com/oti/team2/srdemand/dao/ISrDemandDao.java
  src/main/java/com/oti/team2/srdemand/dto/SrDemand.java
  src/main/java/com/oti/team2/srdemand/dto/SrRequestDto.java
  src/main/java/com/oti/team2/srdemand/dto/SrUpdateDto.java
  src/main/java/com/oti/team2/srdemand/dto/WriterDto.java
  src/main/java/com/oti/team2/srdemand/service/ISrDemandService.java
  src/main/java/com/oti/team2/srdemand/service/SrDemandService.java
  src/main/java/com/oti/team2/system/controller/SystemController.java
  src/main/java/com/oti/team2/system/dao/ISystemDao.java
  src/main/java/com/oti/team2/system/dto/SrSystem.java
  src/main/java/com/oti/team2/system/service/ISystemService.java
  src/main/java/com/oti/team2/system/service/SystemService.java
  src/main/java/com/oti/team2/task/controller/TaskController.java
  src/main/java/com/oti/team2/task/dao/ITaskDao.java
  src/main/java/com/oti/team2/task/dto/SystemTask.java
  src/main/java/com/oti/team2/task/service/ITaskService.java
  src/main/java/com/oti/team2/task/service/TaskService.java
  src/main/resources/mybatis/mapper-config.xml
  src/main/resources/mybatis/mapper/institution.xml
  src/main/resources/mybatis/mapper/member.xml
  src/main/resources/mybatis/mapper/srDemand.xml
  src/main/resources/mybatis/mapper/system.xml
  src/main/resources/mybatis/mapper/systemTask.xml
  src/main/resources/spring/mybatis.xml
  src/main/webapp/WEB-INF/views/management/clientList.jsp
  src/main/webapp/WEB-INF/views/member/myinfo.jsp
  src/main/webapp/WEB-INF/views/srDemand/adminSrDemandList.jsp
  src/main/webapp/WEB-INF/views/srDemand/modal.jsp
  src/main/webapp/WEB-INF/views/srDemand/srDemandListOrigin.jsp
  src/main/webapp/WEB-INF/views/srDemand/userSrDemandList.jsp
Labels: 기능 구현, 추가 구현 필요

#59 [#30] 사원 관리 페이지 검색 및 페이징 기능 추가
  src/main/java/com/oti/team2/admin/controller/AdminController.java
  src/main/java/com/oti/team2/member/controller/MemberController.java
  src/main/java/com/oti/team2/member/dao/IMemberDao.java
  src/main/java/com/oti/team2/member/dto/FilteringMember.java
  src/main/java/com/oti/team2/member/service/IMemberService.java
  src/main/java/com/oti/team2/member/service/MemberService.java
  src/main/java/com/oti/team2/srdemand/controller/SrDemandController.java
  src/main/java/com/oti/team2/util/Auth.java
  src/main/resources/mybatis/mapper/member.xml
  src/main/webapp/WEB-INF/views/fragments/header.jsp
  src/main/webapp/WEB-INF/views/management/employeesList.jsp
Labels: 기능 구현
