Repository OTI-SRM/srm_project, pull requests merged in 2023-03, with the labels that each got.

#71 [#70]SR히스토리 : 개발취소 승인 시 sr요청 상태 변경
  src/main/java/com/oti/team2/progress/dao/IProgressDao.java
  src/main/java/com/oti/team2/progress/service/IProgressService.java
  src/main/java/com/oti/team2/progress/service/ProgressService.java
  src/main/java/com/oti/team2/srdemand/dao/ISrDemandDao.java
  src/main/java/com/oti/team2/srdemand/service/ISrDemandService.java
  src/main/java/com/oti/team2/srdemand/service/SrDemandService.java
  src/main/resources/mybatis/mapper/progress.xml
  src/main/resources/mybatis/mapper/srDemand.xml
Labels: 기능 구현

#69 [#55]산출물 수정 기능 구현
  src/main/java/com/oti/team2/deliverable/controller/DeliverableController.java
  src/main/java/com/oti/team2/deliverable/dao/IDeliverableDao.java
  src/main/java/com/oti/team2/deliverable/service/DeliverableService.java
  src/main/java/com/oti/team2/deliverable/service/IDeliverableService.java
  src/main/java/com/oti/team2/srresource/controller/SrResourceController.java
  src/main/java/com/oti/team2/srresource/dao/ISrResourceDao.java
  src/main/java/com/oti/team2/srresource/dto/SrResource.java
  src/main/java/com/oti/team2/srresource/dto/SrResourceOfDeveloper.java
  src/main/java/com/oti/team2/srresource/service/ISrResourceService.java
  src/main/java/com/oti/team2/srresource/service/SrResourceService.java
  src/main/resources/mybatis/mapper/deliverable.xml
  src/main/resources/mybatis/mapper/srResource.xml
  src/main/webapp/WEB-INF/views/srInfo/addSrResourcesModal.jsp
  src/main/webapp/resources/js/addSrResourcesModal.js
  src/main/webapp/resources/js/deliverables.js
  src/main/webapp/resources/js/srInfo.js
  src/main/webapp/resources/js/srResources.js
Labels: 기능 구현

#74 [#63] 페이징, 필터링 동시 유지 및 사원관리 페이징 offset으로 수정
  src/main/java/com/oti/team2/admin/controller/AdminController.java
  src/main/java/com/oti/team2/srinformation/controller/SrinformationController.java
  src/main/java/com/oti/team2/srinformation/dao/ISrinformationDao.java
  src/main/java/com/oti/team2/srinformation/dto/SrInfoFilter.java
  src/main/java/com/oti/team2/srinformation/service/ISrinformationService.java
  src/main/java/com/oti/team2/srinformation/service/SrinformationService.java
  src/main/java/com/oti/team2/util/pager/Pager.java
  src/main/resources/mybatis/mapper/member.xml
  src/main/resources/mybatis/mapper/srResource.xml
  src/main/resources/mybatis/mapper/srinformation.xml
  src/main/webapp/WEB-INF/views/fragments/pagination.jsp
  src/main/webapp/WEB-INF/views/management/employeesList.jsp
  src/main/webapp/WEB-INF/views/srInfo/srInformationList.jsp
  src/main/webapp/resources/css/pagination.css
  src/main/webapp/resources/js/employeesList.js
  src/main/webapp/resources/js/pagination.js
  src/main/webapp/resources/js/srInfo.js
  src/main/webapp/resources/js/srResources.js
Labels: 기능 구현

#76 고객 관리 필터링 적용 및 컨트롤러 mapping방식 통일
  src/main/java/com/oti/team2/admin/controller/AdminController.java
  src/main/java/com/oti/team2/institution/controller/InstitutionController.java
  src/main/java/com/oti/team2/srinformation/controller/SrinformationController.java
  src/main/java/com/oti/team2/srresource/controller/SrResourceController.java
  src/main/resources/mybatis/mapper/member.xml
  src/main/resources/spring/security.xml
  src/main/webapp/WEB-INF/views/management/clientList.jsp
  src/main/webapp/resources/js/clientList.js
Labels: 기능 구현

#77 [#73] 고객/관리자/개발자변 나의 할일 화면 데이터 구성 구현 완료
  src/main/java/com/oti/team2/exampleController.java
  src/main/java/com/oti/team2/member/controller/LoginController.java
  src/main/java/com/oti/team2/member/controller/MainController.java
  src/main/java/com/oti/team2/member/service/UserService.java
  src/main/java/com/oti/team2/srdemand/controller/SrDemandController.java
  src/main/java/com/oti/team2/srdemand/dao/ISrDemandDao.java
  src/main/java/com/oti/team2/srdemand/dto/MytodoSrListDto.java
  src/main/java/com/oti/team2/srdemand/service/ISrDemandService.java
  src/main/java/com/oti/team2/srdemand/service/SrDemandService.java
  src/main/java/com/oti/team2/srinformation/service/ISrinformationService.java
  src/main/java/com/oti/team2/srinformation/service/SrinformationService.java
  src/main/resources/mybatis/mapper-config.xml
  src/main/resources/mybatis/mapper/srDemand.xml
  src/main/resources/mybatis/mapper/srInformationHistory.xml
  src/main/webapp/WEB-INF/views/fragments/header.jsp
  src/main/webapp/WEB-INF/views/fragments/pagination.jsp
  src/main/webapp/WEB-INF/views/member/my-todo.jsp
  src/main/webapp/WEB-INF/views/srDemand/adminSrDemandList.jsp
  src/main/webapp/resources/js/mytodo.js
  src/main/webapp/resources/js/pagination.js
Labels: 기능 구현, 리뷰 요청

#81 [#80] insert all 동적쿼리 사용하여 진척률 삽입 구현 완료
  src/main/java/com/oti/team2/progress/dao/IProgressDao.java
  src/main/java/com/oti/team2/progress/service/IProgressService.java
  src/main/java/com/oti/team2/progress/service/ProgressService.java
  src/main/java/com/oti/team2/srdemand/dto/SdApprovalDto.java
  src/main/java/com/oti/team2/srdemand/service/ISrDemandService.java
  src/main/java/com/oti/team2/srdemand/service/SrDemandService.java
  src/main/java/com/oti/team2/srinformation/service/SrinformationService.java
  src/main/resources/mybatis/mapper/progress.xml
Labels: 기능 구현

#85 [#39] 처음 자원 정보 입력시 개발중으로 상태 변경
  src/main/java/com/oti/team2/alert/controller/AlertController.java
  src/main/java/com/oti/team2/alert/dto/Alert.java
  src/main/java/com/oti/team2/alert/service/AlertService.java
  src/main/java/com/oti/team2/alert/service/IAlertService.java
  src/main/java/com/oti/team2/srresource/controller/SrResourceController.java
  src/main/java/com/oti/team2/srresource/dto/SrResource.java
  src/main/java/com/oti/team2/srresource/service/ISrResourceService.java
  src/main/java/com/oti/team2/srresource/service/SrResourceService.java
  src/main/java/com/oti/team2/util/sseemitter/SseEmitters.java
  src/main/resources/mybatis/mapper/progress.xml
  src/main/webapp/WEB-INF/views/fragments/top.jsp
  src/main/webapp/resources/js/addSrResourcesModal.js
Labels: 기능 구현

#92 알림 기능 추가 및 기능 수정
  src/main/java/com/oti/team2/alert/controller/AlertController.java
  src/main/java/com/oti/team2/alert/dao/IAlertDao.java
  src/main/java/com/oti/team2/alert/service/AlertService.java
  src/main/java/com/oti/team2/alert/service/IAlertService.java
  src/main/java/com/oti/team2/srresource/controller/SrResourceController.java
  src/main/java/com/oti/team2/util/sseemitter/SseEmitters.java
  src/main/resources/mybatis/mapper/alert.xml
  src/main/webapp/WEB-INF/views/fragments/sidebar.jsp
  src/main/webapp/WEB-INF/views/fragments/top.jsp
  src/main/webapp/WEB-INF/views/member/my-todo.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/resources/js/alert.js
Labels: 기능 구현

#100 sse 서버와 재연결 안되는 문제 해결
  src/main/java/com/oti/team2/alert/controller/AlertController.java
  src/main/java/com/oti/team2/alert/service/AlertService.java
  src/main/java/com/oti/team2/alert/service/IAlertService.java
  src/main/java/com/oti/team2/util/springsecurity/AuthenticationSuccessHandler.java
  src/main/java/com/oti/team2/util/sseemitter/SseEmitters.java
  src/main/resources/mybatis/mapper/progress.xml
  src/main/webapp/WEB-INF/views/srInfo/srInformationList.jsp
  src/main/webapp/resources/js/srInfo.js
Labels: 기능 구현

#104 [#97] 로그인 화면 수정 및 아이디 저장 기능 구현 완료
  src/main/java/com/oti/team2/member/controller/LoginController.java
  src/main/java/com/oti/team2/util/springsecurity/AuthenticationFailureHandler.java
  src/main/java/com/oti/team2/util/springsecurity/AuthenticationSuccessHandler.java
  src/main/webapp/WEB-INF/views/board/qnaList.jsp
  src/main/webapp/WEB-INF/views/fragments/bottom.jsp
  src/main/webapp/WEB-INF/views/fragments/sidebar.jsp
  src/main/webapp/WEB-INF/views/fragments/top.jsp
  src/main/webapp/WEB-INF/views/member/login.jsp
  src/main/webapp/WEB-INF/views/member/my-todo.jsp
  src/main/webapp/WEB-INF/views/srInfo/srInformationList.jsp
  src/main/webapp/resources/assets/css/style.css
  src/main/webapp/resources/js/rememberId.js
  src/main/webapp/resources/js/srResources.js
Labels: 기능 구현

#109 알림 기능 구현중
  src/main/java/com/oti/team2/board/dto/BoardUpdateDto.java
  src/main/java/com/oti/team2/progress/controller/ProgressController.java
  src/main/java/com/oti/team2/srdemand/dto/SrdemandDetail.java
  src/main/java/com/oti/team2/srinformation/dto/SrinformationList.java
  src/main/resources/mybatis/mapper/srDemand.xml
  src/main/webapp/WEB-INF/views/srInfo/srInformationList.jsp
  src/main/webapp/resources/js/srInfo.js
Labels: 기능 구현

#110 [#107] 나의 할일에 히스토리 목록 띄우기, 히스토리 기능 다듬기, 에러페이지 수정, textarea 글자수 계산 기능 구현
  src/main/java/com/oti/team2/GlobalControllerAdvice.java
  src/main/java/com/oti/team2/member/controller/LoginController.java
  src/main/java/com/oti/team2/member/controller/MainController.java
  src/main/java/com/oti/team2/member/controller/MemberController.java
  src/main/java/com/oti/team2/member/dao/IMemberDao.java
  src/main/java/com/oti/team2/member/service/IMemberService.java
  src/main/java/com/oti/team2/member/service/MemberService.java
  src/main/java/com/oti/team2/srdemand/service/ISrDemandService.java
  src/main/java/com/oti/team2/srinformation/controller/SrinformationController.java
  src/main/java/com/oti/team2/srinformation/dao/ISrinformationDao.java
  src/main/java/com/oti/team2/srinformation/dto/SrTotal.java
  src/main/java/com/oti/team2/srinformation/service/ISrinformationService.java
  src/main/java/com/oti/team2/srinformation/service/SrinformationService.java
  src/main/java/com/oti/team2/srinformationhistory/controller/SrInformationHistoryController.java
  src/main/java/com/oti/team2/srinformationhistory/dao/ISrInformationHistoryDao.java
  src/main/java/com/oti/team2/srinformationhistory/dto/MyTodoHistoryListDto.java
  src/main/java/com/oti/team2/srinformationhistory/dto/SrHistoryDetailDto.java
  src/main/java/com/oti/team2/srinformationhistory/service/ISrInformationHistoryService.java
  src/main/java/com/oti/team2/srinformationhistory/service/SrInformationHistoryService.java
  src/main/resources/mybatis/mapper-config.xml
  src/main/resources/mybatis/mapper/member.xml
  src/main/resources/mybatis/mapper/srDemand.xml
  src/main/resources/mybatis/mapper/srInformationHistory.xml
  src/main/webapp/WEB-INF/views/error/runtime.jsp
  src/main/webapp/WEB-INF/views/error/runtimeClient.jsp
  src/main/webapp/WEB-INF/views/fragments/mytodoHstryPager.jsp
  src/main/webapp/WEB-INF/views/fragments/sidebar.jsp
  src/main/webapp/WEB-INF/views/history/addHistoryModal.jsp
  src/main/webapp/WEB-INF/views/history/approvalHistoryModal.jsp
  src/main/webapp/WEB-INF/views/history/approvalInfoHistoryModal.jsp
  src/main/webapp/WEB-INF/views/history/modifyHistoryModal.jsp
  src/main/webapp/WEB-INF/views/member/findPwModal.jsp
  src/main/webapp/WEB-INF/views/member/login.jsp
  src/main/webapp/WEB-INF/views/member/my-todo.jsp
  src/main/webapp/WEB-INF/views/mytodo/srHstryTable.jsp
  src/main/webapp/resources/assets/css/fonts/FontAwesome.otf
  src/main/webapp/resources/assets/css/fonts/fontawesome-webfont.eot
  src/main/webapp/resources/assets/css/fonts/fontawesome-webfont.svg
  src/main/webapp/resources/assets/css/fonts/fontawesome-webfont.ttf
  src/main/webapp/resources/assets/css/fonts/fontawesome-webfont.woff
  src/main/webapp/resources/assets/css/fonts/fontawesome-webfont.woff2
  src/main/webapp/resources/assets/css/style.css
  src/main/webapp/resources/js/addHstryModal.js
  src/main/webapp/resources/js/approvalHstryModal.js
  src/main/webapp/resources/js/approvalInfoHstryModal.js
  src/main/webapp/resources/js/modiHstryModal.js
  src/main/webapp/resources/js/mytodoHstry.js
  src/main/webapp/resources/js/srDemand.js
  src/main/webapp/resources/js/srInfo.js
  src/main/webapp/resources/js/srInfoListHstry.js
  src/main/webapp/resources/js/textarea.js
  src/main/webapp/resources/oti_images/errorClient.jpg
Labels: 기능 구현

#118 [#107] 부서 필터링, 히스토리 페이징 처리 및 취합
  src/main/java/com/oti/team2/admin/controller/AdminController.java
  src/main/java/com/oti/team2/department/dao/IDepartmentDao.java
  src/main/java/com/oti/team2/department/dto/DeptFilterDto.java
  src/main/java/com/oti/team2/department/service/DepartmentService.java
  src/main/java/com/oti/team2/department/service/IDepartmentService.java
  src/main/java/com/oti/team2/member/controller/JoinController.java
  src/main/java/com/oti/team2/member/controller/MainController.java
  src/main/java/com/oti/team2/srinformation/controller/SrinformationController.java
  src/main/java/com/oti/team2/srinformation/dto/SrTotal.java
  src/main/java/com/oti/team2/srinformationhistory/controller/SrInformationHistoryController.java
  src/main/java/com/oti/team2/srinformationhistory/dao/ISrInformationHistoryDao.java
  src/main/java/com/oti/team2/srinformationhistory/dto/MyTodoHistoryListDto.java
  src/main/java/com/oti/team2/srinformationhistory/service/ISrInformationHistoryService.java
  src/main/java/com/oti/team2/srinformationhistory/service/SrInformationHistoryService.java
  src/main/java/com/oti/team2/util/pager/Pager.java
  src/main/resources/mybatis/mapper/department.xml
  src/main/resources/mybatis/mapper/srInformationHistory.xml
  src/main/webapp/WEB-INF/views/fragments/mytodoHstryPager.jsp
  src/main/webapp/WEB-INF/views/fragments/mytodoPager.jsp
  src/main/webapp/WEB-INF/views/management/departmentsList.jsp
  src/main/webapp/WEB-INF/views/member/my-todo.jsp
  src/main/webapp/WEB-INF/views/mytodo/srHstryTable.jsp
  src/main/webapp/WEB-INF/views/srDemand/adminSrDemandList.jsp
  src/main/webapp/WEB-INF/views/srDemand/userSrDemandList.jsp
  src/main/webapp/WEB-INF/views/srInfo/srInformationList.jsp
  src/main/webapp/resources/js/approvalInfoHstryModal.js
  src/main/webapp/resources/js/mytodoHstry.js
  src/main/webapp/resources/js/srDemandListHstry.js
  src/main/webapp/resources/js/srInfo.js
  src/main/webapp/resources/js/srInfoListHstry.js
Labels: 기능 구현

#123 [#119] 비밀번호 찾기 구현 완료 및 취합
  pom.xml
  src/main/java/com/oti/team2/member/controller/MemberController.java
  src/main/java/com/oti/team2/member/dao/IMemberDao.java
  src/main/java/com/oti/team2/member/dto/MemberDto.java
  src/main/java/com/oti/team2/member/service/IJoinService.java
  src/main/java/com/oti/team2/member/service/IMemberService.java
  src/main/java/com/oti/team2/member/service/JoinService.java
  src/main/java/com/oti/team2/member/service/MemberService.java
  src/main/resources/mybatis/mapper-config.xml
  src/main/resources/mybatis/mapper/member.xml
  src/main/resources/spring/mailsender.xml
  src/main/resources/spring/security.xml
  src/main/webapp/WEB-INF/views/member/findPwModal.jsp
  src/main/webapp/resources/js/findPwModal.js
Labels: 기능 구현

#135 [#64]관리자, 나의 처리 보기로 담당 시스템 진척이 나오도록 수정, 알람을 눌렀을때 사라지지않도록 수정
  src/main/java/com/oti/team2/alert/service/AlertService.java
  src/main/java/com/oti/team2/srinformation/controller/SrinformationController.java
  src/main/java/com/oti/team2/srinformation/dao/ISrinformationDao.java
  src/main/java/com/oti/team2/srinformation/service/ISrinformationService.java
  src/main/java/com/oti/team2/srinformation/service/SrinformationService.java
  src/main/resources/mybatis/mapper/srinformation.xml
Labels: 기능 구현

#143 [#142] srInfo 개발자 버튼 복구 및 모달 수정
  src/main/java/com/oti/team2/member/controller/MemberController.java
  src/main/java/com/oti/team2/srinformation/controller/SrinformationController.java
  src/main/resources/mybatis/mapper/srInformationHistory.xml
  src/main/webapp/resources/js/approvalHstryModal.js
  src/main/webapp/resources/js/approvalInfoHstryModal.js
  src/main/webapp/resources/js/srInfo.js
Labels: 기능 구현

#148 [#124] SR요청상세, SR처리 정보 탭으로 전환하도록 변경
  src/main/webapp/WEB-INF/views/srInfo/addSrResourcesModal.jsp
  src/main/webapp/WEB-INF/views/srInfo/srInformationList.jsp
  src/main/webapp/resources/js/alert.js
  src/main/webapp/resources/js/srInfo.js
  src/main/webapp/resources/js/srResources.js
Labels: 기능 구현, 화면 구현

#152 [#144] 비밀번호 찾기, 히스토리 수정 기능 보완 및 취합
  src/main/java/com/oti/team2/member/controller/MemberController.java
  src/main/java/com/oti/team2/member/dao/IMemberDao.java
  src/main/java/com/oti/team2/srinformationhistory/dto/SrHistoryDetailDto.java
  src/main/java/com/oti/team2/srinformationhistory/dto/SrInformationHistory.java
  src/main/resources/spring/security.xml
  src/main/webapp/WEB-INF/views/history/approvalHistoryModal.jsp
  src/main/webapp/WEB-INF/views/history/approvalInfoHistoryModal.jsp
  src/main/webapp/WEB-INF/views/member/findPwModal.jsp
  src/main/webapp/WEB-INF/views/srInfo/srInformationList.jsp
  src/main/webapp/resources/js/approvalHstryModal.js
  src/main/webapp/resources/js/approvalInfoHstryModal.js
  src/main/webapp/resources/js/findPwModal.js
Labels: 기능 구현

#163 자원 정보 모달 열릴시 역할 목록 보이도록 수정
  src/main/webapp/resources/js/addSrResourcesModal.js
Labels: 기능 구현

#164 [#156] 취합 후 include된 js 수정
  src/main/java/com/oti/team2/srdemand/service/SrDemandService.java
  src/main/webapp/WEB-INF/views/srDemand/userSrDemandList.jsp
  src/main/webapp/resources/js/approvalInfoHstryModal.js
Labels: 기능 구현

#166 ui 수정
  src/main/webapp/WEB-INF/views/srInfo/addSrResourcesModal.jsp
  src/main/webapp/WEB-INF/views/srInfo/srInformationList.jsp
  src/main/webapp/resources/js/addSrResourcesModal.js
Labels: 화면 구현
